### ISSUE TITLE
Planering

### ISSUE THREAD

**Issue by anhility** [anhility/DVA227#7]
- [x] Starta planering
- [x] ~~Projektplan~~ #25 - ignorerad
- [x] Detaljerad WBS med aktivitetslista #14 
- [x] Logisk Nätplan med Kritiska Linjen #15 
- [x] Tidsplan & Gantt-schema #16
- [x] ~~Resurshantering~~ #18 - ignorerad
- [x] ~~Kostnadskalkyl & budget~~ #19 - ignorerad
- [x] ~~Riskhantering~~ #20
- [x] ~~Produktkvalitet~~ #21
- [x] Avsluta planering

**Comment by anhility** [comment]
## Projektplan
Ignoreras på grund av tidsbrist.

**Comment by anhility** [comment]
## Kritiska Linjen #17
Reserverad

**Comment by anhility** [comment]
## Tidsplan & Gantt-schema #16 
Reserverad

**Comment by anhility** [comment]
## Resurshantering #18 
Reserverad

**Comment by anhility** [comment]
## Kostnadskalkyl & budget #19 
Reserverad

**Comment by anhility** [comment]
## Riskhantering #20 
Reserverad

**Comment by anhility** [comment]
## Produktkvalitet #21 
Reserverad
